-- =====================================================================
-- Coach OS — Migration 3 : données de référence communes
-- 18 mouvements, 170 exercices (organization_id NULL = bibliothèque commune)
-- Généré par gen_ref.py. Liens vidéo à renseigner ensuite (champ video_url).
-- =====================================================================

insert into public.movements (slug, name, description) values
  ('squat', 'Squat', 'Flexion/extension genou-hanche, charge à dominante quadriceps'),
  ('lunge', 'Fente / unilatéral jambe', 'Appuis décalés ou unilatéraux'),
  ('hinge', 'Charnière de hanche', 'Dominante chaîne postérieure'),
  ('horizontal_push', 'Poussée horizontale', 'Pectoraux, triceps, deltoïdes antérieurs'),
  ('vertical_push', 'Poussée verticale', 'Épaules et triceps'),
  ('horizontal_pull', 'Tirage horizontal', 'Dos et biceps'),
  ('vertical_pull', 'Tirage vertical', 'Grand dorsal et biceps'),
  ('core', 'Gainage / tronc', 'Stabilité et flexion/rotation du tronc'),
  ('carry', 'Port de charge / traîneau', 'Déplacements chargés'),
  ('olympic', 'Haltérophilie', 'Mouvements olympiques et dérivés'),
  ('jump_plyo', 'Sauts / pliométrie', 'Puissance, réactivité, lancers'),
  ('calf_ankle', 'Mollet / cheville', null),
  ('arm_isolation', 'Bras (isolation)', null),
  ('shoulder_accessory', 'Épaule (accessoires)', null),
  ('running', 'Course à pied', null),
  ('machine_cardio', 'Ergomètres et cardio', null),
  ('conditioning', 'Conditioning / métabolique', null),
  ('mobility', 'Mobilité', null);

insert into public.exercises (movement_id, name, primary_muscles, secondary_muscles, equipment, level, unilateral)
select m.id, v.name, v.pm, v.sm, v.eq, v.lvl, v.uni
from (values
  ('Back squat', 'squat', '{quadriceps,glutes}'::text[], '{adductors,lower_back}'::text[], '{barbell,rack}'::text[], 'intermediate', false),
  ('Front squat', 'squat', '{quadriceps}'::text[], '{glutes,abs,upper_back}'::text[], '{barbell,rack}'::text[], 'advanced', false),
  ('Goblet squat', 'squat', '{quadriceps,glutes}'::text[], '{abs}'::text[], '{dumbbell,kettlebell}'::text[], 'beginner', false),
  ('Hack squat', 'squat', '{quadriceps}'::text[], '{glutes}'::text[], '{machine}'::text[], 'beginner', false),
  ('Leg press', 'squat', '{quadriceps,glutes}'::text[], '{adductors}'::text[], '{machine}'::text[], 'beginner', false),
  ('Box squat', 'squat', '{quadriceps,glutes}'::text[], '{hamstrings}'::text[], '{barbell,rack,box}'::text[], 'intermediate', false),
  ('Safety bar squat', 'squat', '{quadriceps,glutes}'::text[], '{upper_back}'::text[], '{barbell,rack}'::text[], 'intermediate', false),
  ('Zercher squat', 'squat', '{quadriceps,glutes}'::text[], '{abs,biceps}'::text[], '{barbell,rack}'::text[], 'advanced', false),
  ('Overhead squat', 'squat', '{quadriceps}'::text[], '{front_delts,abs,upper_back}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Bodyweight squat', 'squat', '{quadriceps,glutes}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Landmine squat', 'squat', '{quadriceps}'::text[], '{glutes,abs}'::text[], '{barbell,landmine}'::text[], 'beginner', false),
  ('Belt squat', 'squat', '{quadriceps,glutes}'::text[], '{}'::text[], '{machine}'::text[], 'beginner', false),
  ('Smith machine squat', 'squat', '{quadriceps,glutes}'::text[], '{}'::text[], '{machine}'::text[], 'beginner', false),
  ('Pause back squat', 'squat', '{quadriceps,glutes}'::text[], '{lower_back}'::text[], '{barbell,rack}'::text[], 'intermediate', false),
  ('Walking lunge', 'lunge', '{quadriceps,glutes}'::text[], '{hamstrings}'::text[], '{dumbbell}'::text[], 'intermediate', true),
  ('Reverse lunge', 'lunge', '{quadriceps,glutes}'::text[], '{hamstrings}'::text[], '{dumbbell,barbell}'::text[], 'beginner', true),
  ('Bulgarian split squat', 'lunge', '{quadriceps,glutes}'::text[], '{adductors}'::text[], '{dumbbell,bench}'::text[], 'intermediate', true),
  ('Split squat', 'lunge', '{quadriceps,glutes}'::text[], '{}'::text[], '{bodyweight,dumbbell}'::text[], 'beginner', true),
  ('Step-up', 'lunge', '{quadriceps,glutes}'::text[], '{}'::text[], '{dumbbell,box}'::text[], 'beginner', true),
  ('Lateral lunge', 'lunge', '{adductors,glutes}'::text[], '{quadriceps}'::text[], '{dumbbell,bodyweight}'::text[], 'beginner', true),
  ('Curtsy lunge', 'lunge', '{glutes,abductors}'::text[], '{quadriceps}'::text[], '{dumbbell,bodyweight}'::text[], 'intermediate', true),
  ('Front-rack lunge', 'lunge', '{quadriceps,glutes}'::text[], '{abs}'::text[], '{barbell,rack}'::text[], 'advanced', true),
  ('Sandbag lunge', 'lunge', '{quadriceps,glutes}'::text[], '{abs}'::text[], '{sandbag}'::text[], 'intermediate', true),
  ('Lateral step-up', 'lunge', '{glutes,quadriceps}'::text[], '{abductors}'::text[], '{dumbbell,box}'::text[], 'beginner', true),
  ('Conventional deadlift', 'hinge', '{glutes,hamstrings,lower_back}'::text[], '{quadriceps,upper_back,forearms}'::text[], '{barbell}'::text[], 'intermediate', false),
  ('Sumo deadlift', 'hinge', '{glutes,adductors,quadriceps}'::text[], '{hamstrings,lower_back}'::text[], '{barbell}'::text[], 'intermediate', false),
  ('Trap bar deadlift', 'hinge', '{quadriceps,glutes,hamstrings}'::text[], '{lower_back,forearms}'::text[], '{trap_bar}'::text[], 'beginner', false),
  ('Romanian deadlift', 'hinge', '{hamstrings,glutes}'::text[], '{lower_back}'::text[], '{barbell,dumbbell}'::text[], 'intermediate', false),
  ('Stiff-leg deadlift', 'hinge', '{hamstrings}'::text[], '{glutes,lower_back}'::text[], '{barbell}'::text[], 'intermediate', false),
  ('Single-leg Romanian deadlift', 'hinge', '{hamstrings,glutes}'::text[], '{abductors,abs}'::text[], '{dumbbell,kettlebell}'::text[], 'intermediate', true),
  ('Good morning', 'hinge', '{hamstrings,lower_back}'::text[], '{glutes}'::text[], '{barbell,rack}'::text[], 'advanced', false),
  ('Hip thrust', 'hinge', '{glutes}'::text[], '{hamstrings}'::text[], '{barbell,bench}'::text[], 'beginner', false),
  ('Glute bridge', 'hinge', '{glutes}'::text[], '{hamstrings}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Kettlebell swing', 'hinge', '{glutes,hamstrings}'::text[], '{lower_back,abs}'::text[], '{kettlebell}'::text[], 'beginner', false),
  ('Cable pull-through', 'hinge', '{glutes,hamstrings}'::text[], '{}'::text[], '{cable}'::text[], 'beginner', false),
  ('45-degree back extension', 'hinge', '{lower_back,glutes}'::text[], '{hamstrings}'::text[], '{machine}'::text[], 'beginner', false),
  ('Nordic hamstring curl', 'hinge', '{hamstrings}'::text[], '{calves}'::text[], '{bodyweight}'::text[], 'advanced', false),
  ('Lying leg curl', 'hinge', '{hamstrings}'::text[], '{}'::text[], '{machine}'::text[], 'beginner', false),
  ('Seated leg curl', 'hinge', '{hamstrings}'::text[], '{}'::text[], '{machine}'::text[], 'beginner', false),
  ('Deficit deadlift', 'hinge', '{glutes,hamstrings,lower_back}'::text[], '{quadriceps}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Bench press', 'horizontal_push', '{chest,triceps}'::text[], '{front_delts}'::text[], '{barbell,bench,rack}'::text[], 'intermediate', false),
  ('Incline bench press', 'horizontal_push', '{chest,front_delts}'::text[], '{triceps}'::text[], '{barbell,bench,rack}'::text[], 'intermediate', false),
  ('Dumbbell bench press', 'horizontal_push', '{chest,triceps}'::text[], '{front_delts}'::text[], '{dumbbell,bench}'::text[], 'beginner', false),
  ('Incline dumbbell press', 'horizontal_push', '{chest,front_delts}'::text[], '{triceps}'::text[], '{dumbbell,bench}'::text[], 'beginner', false),
  ('Close-grip bench press', 'horizontal_push', '{triceps,chest}'::text[], '{front_delts}'::text[], '{barbell,bench,rack}'::text[], 'intermediate', false),
  ('Push-up', 'horizontal_push', '{chest,triceps}'::text[], '{front_delts,abs}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Weighted push-up', 'horizontal_push', '{chest,triceps}'::text[], '{front_delts,abs}'::text[], '{bodyweight,plate}'::text[], 'intermediate', false),
  ('Parallel bar dip', 'horizontal_push', '{chest,triceps}'::text[], '{front_delts}'::text[], '{dip_bars}'::text[], 'intermediate', false),
  ('Cable fly', 'horizontal_push', '{chest}'::text[], '{front_delts}'::text[], '{cable}'::text[], 'beginner', false),
  ('Machine chest press', 'horizontal_push', '{chest,triceps}'::text[], '{front_delts}'::text[], '{machine}'::text[], 'beginner', false),
  ('Floor press', 'horizontal_push', '{triceps,chest}'::text[], '{front_delts}'::text[], '{barbell,dumbbell}'::text[], 'beginner', false),
  ('Decline bench press', 'horizontal_push', '{chest}'::text[], '{triceps}'::text[], '{barbell,bench,rack}'::text[], 'intermediate', false),
  ('Overhead press', 'vertical_push', '{front_delts,triceps}'::text[], '{side_delts,upper_back,abs}'::text[], '{barbell,rack}'::text[], 'intermediate', false),
  ('Seated dumbbell shoulder press', 'vertical_push', '{front_delts,side_delts}'::text[], '{triceps}'::text[], '{dumbbell,bench}'::text[], 'beginner', false),
  ('Push press', 'vertical_push', '{front_delts,triceps}'::text[], '{quadriceps,side_delts}'::text[], '{barbell,rack}'::text[], 'intermediate', false),
  ('Landmine press', 'vertical_push', '{front_delts,chest}'::text[], '{triceps,abs}'::text[], '{barbell,landmine}'::text[], 'beginner', true),
  ('Arnold press', 'vertical_push', '{front_delts,side_delts}'::text[], '{triceps}'::text[], '{dumbbell}'::text[], 'intermediate', false),
  ('Handstand push-up', 'vertical_push', '{front_delts,triceps}'::text[], '{side_delts,abs}'::text[], '{bodyweight}'::text[], 'advanced', false),
  ('Z press', 'vertical_push', '{front_delts}'::text[], '{triceps,abs}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Barbell row', 'horizontal_pull', '{lats,upper_back}'::text[], '{biceps,lower_back,rear_delts}'::text[], '{barbell}'::text[], 'intermediate', false),
  ('Dumbbell row', 'horizontal_pull', '{lats,upper_back}'::text[], '{biceps,rear_delts}'::text[], '{dumbbell,bench}'::text[], 'beginner', true),
  ('Chest-supported row', 'horizontal_pull', '{upper_back,lats}'::text[], '{biceps,rear_delts}'::text[], '{machine,dumbbell,bench}'::text[], 'beginner', false),
  ('Seated cable row', 'horizontal_pull', '{lats,upper_back}'::text[], '{biceps}'::text[], '{cable}'::text[], 'beginner', false),
  ('Inverted row', 'horizontal_pull', '{upper_back,lats}'::text[], '{biceps,abs}'::text[], '{bodyweight,rack}'::text[], 'beginner', false),
  ('Pendlay row', 'horizontal_pull', '{upper_back,lats}'::text[], '{lower_back,biceps}'::text[], '{barbell}'::text[], 'advanced', false),
  ('T-bar row', 'horizontal_pull', '{upper_back,lats}'::text[], '{biceps,lower_back}'::text[], '{barbell,landmine}'::text[], 'intermediate', false),
  ('Face pull', 'horizontal_pull', '{rear_delts,upper_back}'::text[], '{traps}'::text[], '{cable,band}'::text[], 'beginner', false),
  ('Meadows row', 'horizontal_pull', '{lats,upper_back}'::text[], '{biceps,rear_delts}'::text[], '{barbell,landmine}'::text[], 'intermediate', true),
  ('Machine row', 'horizontal_pull', '{lats,upper_back}'::text[], '{biceps}'::text[], '{machine}'::text[], 'beginner', false),
  ('Seal row', 'horizontal_pull', '{upper_back,lats}'::text[], '{biceps,rear_delts}'::text[], '{barbell,bench}'::text[], 'intermediate', false),
  ('Pull-up', 'vertical_pull', '{lats}'::text[], '{biceps,upper_back,abs}'::text[], '{pullup_bar}'::text[], 'intermediate', false),
  ('Chin-up', 'vertical_pull', '{lats,biceps}'::text[], '{upper_back}'::text[], '{pullup_bar}'::text[], 'intermediate', false),
  ('Lat pulldown', 'vertical_pull', '{lats}'::text[], '{biceps,upper_back}'::text[], '{cable,machine}'::text[], 'beginner', false),
  ('Neutral-grip pull-up', 'vertical_pull', '{lats}'::text[], '{biceps,upper_back}'::text[], '{pullup_bar}'::text[], 'intermediate', false),
  ('Weighted pull-up', 'vertical_pull', '{lats}'::text[], '{biceps,upper_back}'::text[], '{pullup_bar,plate}'::text[], 'advanced', false),
  ('Single-arm lat pulldown', 'vertical_pull', '{lats}'::text[], '{biceps}'::text[], '{cable}'::text[], 'beginner', true),
  ('Straight-arm pulldown', 'vertical_pull', '{lats}'::text[], '{abs}'::text[], '{cable}'::text[], 'beginner', false),
  ('Assisted pull-up', 'vertical_pull', '{lats}'::text[], '{biceps}'::text[], '{machine,band}'::text[], 'beginner', false),
  ('Plank', 'core', '{abs}'::text[], '{obliques,lower_back}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Side plank', 'core', '{obliques}'::text[], '{abs,abductors}'::text[], '{bodyweight}'::text[], 'beginner', true),
  ('Dead bug', 'core', '{abs}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Bird dog', 'core', '{lower_back,glutes}'::text[], '{abs}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Pallof press', 'core', '{obliques,abs}'::text[], '{}'::text[], '{cable,band}'::text[], 'beginner', true),
  ('Hanging knee raise', 'core', '{abs,hip_flexors}'::text[], '{forearms}'::text[], '{pullup_bar}'::text[], 'intermediate', false),
  ('Hanging leg raise', 'core', '{abs,hip_flexors}'::text[], '{forearms}'::text[], '{pullup_bar}'::text[], 'advanced', false),
  ('Ab wheel rollout', 'core', '{abs}'::text[], '{lats,front_delts}'::text[], '{ab_wheel}'::text[], 'advanced', false),
  ('Cable crunch', 'core', '{abs}'::text[], '{}'::text[], '{cable}'::text[], 'beginner', false),
  ('Russian twist', 'core', '{obliques}'::text[], '{abs}'::text[], '{medicine_ball,bodyweight}'::text[], 'beginner', false),
  ('Hollow hold', 'core', '{abs}'::text[], '{hip_flexors}'::text[], '{bodyweight}'::text[], 'intermediate', false),
  ('Copenhagen plank', 'core', '{adductors,obliques}'::text[], '{abs}'::text[], '{bench}'::text[], 'advanced', true),
  ('Bear crawl', 'core', '{abs,front_delts}'::text[], '{quadriceps}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('V-up', 'core', '{abs}'::text[], '{hip_flexors}'::text[], '{bodyweight}'::text[], 'intermediate', false),
  ('Toes to bar', 'core', '{abs,hip_flexors}'::text[], '{lats,forearms}'::text[], '{pullup_bar}'::text[], 'advanced', false),
  ('Farmer carry', 'carry', '{forearms,traps}'::text[], '{glutes,abs,upper_back}'::text[], '{dumbbell,kettlebell,trap_bar}'::text[], 'beginner', false),
  ('Suitcase carry', 'carry', '{obliques,forearms}'::text[], '{traps,glutes}'::text[], '{dumbbell,kettlebell}'::text[], 'beginner', true),
  ('Sandbag carry', 'carry', '{abs,upper_back}'::text[], '{biceps,glutes}'::text[], '{sandbag}'::text[], 'beginner', false),
  ('Sled push', 'carry', '{quadriceps,glutes}'::text[], '{calves,abs}'::text[], '{sled}'::text[], 'beginner', false),
  ('Sled pull', 'carry', '{hamstrings,glutes}'::text[], '{upper_back,forearms}'::text[], '{sled}'::text[], 'beginner', false),
  ('Overhead carry', 'carry', '{front_delts,abs}'::text[], '{traps,triceps}'::text[], '{dumbbell,kettlebell}'::text[], 'intermediate', true),
  ('Front-rack carry', 'carry', '{abs,upper_back}'::text[], '{quadriceps,forearms}'::text[], '{kettlebell}'::text[], 'intermediate', true),
  ('Power clean', 'olympic', '{glutes,hamstrings,traps}'::text[], '{quadriceps,upper_back}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Hang power clean', 'olympic', '{glutes,hamstrings,traps}'::text[], '{quadriceps}'::text[], '{barbell}'::text[], 'intermediate', false),
  ('Squat clean', 'olympic', '{quadriceps,glutes,traps}'::text[], '{hamstrings,upper_back}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Power snatch', 'olympic', '{glutes,traps,front_delts}'::text[], '{hamstrings,quadriceps}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Snatch', 'olympic', '{quadriceps,glutes,traps}'::text[], '{front_delts,upper_back}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Clean and jerk', 'olympic', '{full_body}'::text[], '{}'::text[], '{barbell}'::text[], 'advanced', false),
  ('Push jerk', 'olympic', '{front_delts,triceps}'::text[], '{quadriceps}'::text[], '{barbell,rack}'::text[], 'advanced', false),
  ('Dumbbell snatch', 'olympic', '{glutes,front_delts}'::text[], '{hamstrings,traps}'::text[], '{dumbbell}'::text[], 'intermediate', true),
  ('Kettlebell clean', 'olympic', '{glutes,hamstrings}'::text[], '{forearms,biceps}'::text[], '{kettlebell}'::text[], 'intermediate', true),
  ('Box jump', 'jump_plyo', '{quadriceps,glutes}'::text[], '{calves}'::text[], '{box}'::text[], 'beginner', false),
  ('Broad jump', 'jump_plyo', '{glutes,quadriceps}'::text[], '{hamstrings,calves}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Countermovement jump', 'jump_plyo', '{quadriceps,glutes}'::text[], '{calves}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Depth jump', 'jump_plyo', '{quadriceps,calves}'::text[], '{glutes}'::text[], '{box}'::text[], 'advanced', false),
  ('Squat jump', 'jump_plyo', '{quadriceps,glutes}'::text[], '{calves}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Skater bound', 'jump_plyo', '{glutes,abductors}'::text[], '{quadriceps,calves}'::text[], '{bodyweight}'::text[], 'intermediate', true),
  ('Single-leg hop', 'jump_plyo', '{calves,quadriceps}'::text[], '{glutes}'::text[], '{bodyweight}'::text[], 'intermediate', true),
  ('Pogo hops', 'jump_plyo', '{calves}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Medicine ball slam', 'jump_plyo', '{abs,lats}'::text[], '{front_delts}'::text[], '{medicine_ball}'::text[], 'beginner', false),
  ('Medicine ball rotational throw', 'jump_plyo', '{obliques}'::text[], '{glutes,front_delts}'::text[], '{medicine_ball}'::text[], 'beginner', true),
  ('Burpee broad jump', 'jump_plyo', '{full_body}'::text[], '{}'::text[], '{bodyweight}'::text[], 'intermediate', false),
  ('Standing calf raise', 'calf_ankle', '{calves}'::text[], '{}'::text[], '{machine,dumbbell}'::text[], 'beginner', false),
  ('Seated calf raise', 'calf_ankle', '{calves}'::text[], '{}'::text[], '{machine}'::text[], 'beginner', false),
  ('Single-leg calf raise', 'calf_ankle', '{calves}'::text[], '{}'::text[], '{bodyweight,dumbbell}'::text[], 'beginner', true),
  ('Tibialis raise', 'calf_ankle', '{calves}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Jump rope', 'calf_ankle', '{calves}'::text[], '{forearms}'::text[], '{jump_rope}'::text[], 'beginner', false),
  ('Barbell curl', 'arm_isolation', '{biceps}'::text[], '{forearms}'::text[], '{barbell}'::text[], 'beginner', false),
  ('Dumbbell curl', 'arm_isolation', '{biceps}'::text[], '{forearms}'::text[], '{dumbbell}'::text[], 'beginner', false),
  ('Hammer curl', 'arm_isolation', '{biceps,forearms}'::text[], '{}'::text[], '{dumbbell}'::text[], 'beginner', false),
  ('Preacher curl', 'arm_isolation', '{biceps}'::text[], '{}'::text[], '{barbell,dumbbell,bench}'::text[], 'beginner', false),
  ('Cable triceps pushdown', 'arm_isolation', '{triceps}'::text[], '{}'::text[], '{cable}'::text[], 'beginner', false),
  ('Overhead triceps extension', 'arm_isolation', '{triceps}'::text[], '{}'::text[], '{cable,dumbbell}'::text[], 'beginner', false),
  ('Skull crusher', 'arm_isolation', '{triceps}'::text[], '{}'::text[], '{barbell,bench}'::text[], 'intermediate', false),
  ('Cable curl', 'arm_isolation', '{biceps}'::text[], '{}'::text[], '{cable}'::text[], 'beginner', false),
  ('Lateral raise', 'shoulder_accessory', '{side_delts}'::text[], '{}'::text[], '{dumbbell,cable}'::text[], 'beginner', false),
  ('Rear delt fly', 'shoulder_accessory', '{rear_delts}'::text[], '{upper_back}'::text[], '{dumbbell,cable,machine}'::text[], 'beginner', false),
  ('Cable external rotation', 'shoulder_accessory', '{rear_delts}'::text[], '{}'::text[], '{cable,band}'::text[], 'beginner', true),
  ('Y-T-W raise', 'shoulder_accessory', '{upper_back,rear_delts}'::text[], '{traps}'::text[], '{dumbbell,band}'::text[], 'beginner', false),
  ('Scapular pull-up', 'shoulder_accessory', '{traps,lats}'::text[], '{}'::text[], '{pullup_bar}'::text[], 'beginner', false),
  ('Easy run', 'running', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{none}'::text[], 'beginner', false),
  ('Tempo run', 'running', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{none}'::text[], 'intermediate', false),
  ('Interval run', 'running', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{track}'::text[], 'intermediate', false),
  ('Hill repeats', 'running', '{quadriceps,glutes,calves}'::text[], '{hamstrings}'::text[], '{none}'::text[], 'intermediate', false),
  ('Strides', 'running', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{none}'::text[], 'beginner', false),
  ('Long run', 'running', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{none}'::text[], 'beginner', false),
  ('Fartlek', 'running', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{none}'::text[], 'intermediate', false),
  ('Race-pace run', 'running', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{none}'::text[], 'intermediate', false),
  ('Row ergometer', 'machine_cardio', '{lats,quadriceps}'::text[], '{upper_back,hamstrings}'::text[], '{rower}'::text[], 'beginner', false),
  ('SkiErg', 'machine_cardio', '{lats,triceps}'::text[], '{abs,glutes}'::text[], '{skierg}'::text[], 'beginner', false),
  ('Bike endurance', 'machine_cardio', '{quadriceps,glutes}'::text[], '{calves,hamstrings}'::text[], '{bike}'::text[], 'beginner', false),
  ('Bike intervals', 'machine_cardio', '{quadriceps,glutes}'::text[], '{calves,hamstrings}'::text[], '{bike}'::text[], 'intermediate', false),
  ('Assault bike', 'machine_cardio', '{full_body}'::text[], '{}'::text[], '{assault_bike}'::text[], 'beginner', false),
  ('Treadmill run', 'machine_cardio', '{quadriceps,calves}'::text[], '{glutes,hamstrings}'::text[], '{treadmill}'::text[], 'beginner', false),
  ('Wall ball', 'conditioning', '{quadriceps,front_delts}'::text[], '{glutes,abs}'::text[], '{medicine_ball}'::text[], 'beginner', false),
  ('Burpee', 'conditioning', '{full_body}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Thruster', 'conditioning', '{quadriceps,front_delts}'::text[], '{glutes,triceps}'::text[], '{barbell,dumbbell}'::text[], 'intermediate', false),
  ('Double-under', 'conditioning', '{calves}'::text[], '{forearms}'::text[], '{jump_rope}'::text[], 'intermediate', false),
  ('Devil press', 'conditioning', '{full_body}'::text[], '{}'::text[], '{dumbbell}'::text[], 'intermediate', false),
  ('Battle rope waves', 'conditioning', '{front_delts,abs}'::text[], '{forearms}'::text[], '{battle_rope}'::text[], 'beginner', false),
  ('Sandbag over shoulder', 'conditioning', '{glutes,upper_back}'::text[], '{hamstrings,biceps}'::text[], '{sandbag}'::text[], 'intermediate', false),
  ('90/90 hip switch', 'mobility', '{hip_flexors,glutes}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Couch stretch', 'mobility', '{hip_flexors,quadriceps}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', true),
  ('World''s greatest stretch', 'mobility', '{hip_flexors,hamstrings}'::text[], '{upper_back}'::text[], '{bodyweight}'::text[], 'beginner', true),
  ('Thoracic open book', 'mobility', '{upper_back}'::text[], '{obliques}'::text[], '{bodyweight}'::text[], 'beginner', true),
  ('Cat-cow', 'mobility', '{lower_back,abs}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Ankle dorsiflexion wall drill', 'mobility', '{calves}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', true),
  ('Band shoulder dislocates', 'mobility', '{front_delts,upper_back}'::text[], '{}'::text[], '{band}'::text[], 'beginner', false),
  ('Deep squat hold', 'mobility', '{adductors,glutes}'::text[], '{calves}'::text[], '{bodyweight}'::text[], 'beginner', false),
  ('Pigeon stretch', 'mobility', '{glutes,hip_flexors}'::text[], '{}'::text[], '{bodyweight}'::text[], 'beginner', true),
  ('Thread the needle', 'mobility', '{upper_back}'::text[], '{rear_delts}'::text[], '{bodyweight}'::text[], 'beginner', true),
  ('Cossack squat', 'mobility', '{adductors,glutes}'::text[], '{quadriceps}'::text[], '{bodyweight}'::text[], 'intermediate', true)
) as v(name, slug, pm, sm, eq, lvl, uni)
join public.movements m on m.slug = v.slug;
